(() => {
const cfg=window.SPRITESWAP_CONFIG||{}, sb=(cfg.supabaseUrl&&cfg.supabaseAnonKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null, sprites=window.SPRITES||[];
const $=s=>document.querySelector(s), P=new URLSearchParams(location.search), esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])), fmt=v=>new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
const ico=n=>({bell:'<svg class="icon" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>',msg:'<svg class="icon" viewBox="0 0 24 24"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/></svg>',user:'<svg class="icon" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',grid:'<svg class="icon" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>',plus:'<svg class="icon" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>'}[n]||'');
const sprite=id=>sprites.find(s=>s.id===id), avatar=p=>p?.avatar_url||'assets/spriteswap-sprite-logo-128.png', name=p=>p?.discord_name||p?.username||'Collector';
async function ses(){return sb?(await sb.auth.getSession()).data.session:null} async function profile(id){return (await sb.from('profiles').select('*').eq('id',id).single()).data} async function mine(){const s=await ses();return s?profile(s.user.id):null}
function header(){const el=$('#pageHeader');if(!el)return;el.innerHTML=`<header class="site-header"><div class="header-inner"><a class="brand" href="/"><span class="brand-mark"><img src="assets/spriteswap-sprite-logo-128.png"></span><span>SPRITE<span class="brand-pop">SWAP</span></span></a><div class="header-search"><span>⌕</span><input placeholder="Search sprites, traders or IDs" onkeydown="if(event.key==='Enter')location.href='/?q='+encodeURIComponent(this.value)+'#sprites'"><kbd>/</kbd></div><nav><a href="/#trades">Trades</a><a href="/#sprites">Sprite Index</a><a href="/#community">Community</a><button id="pageMessages" class="nav-icon-btn" aria-label="Messages">${ico('msg')}</button><button id="pageNotifications" class="nav-icon-btn" aria-label="Notifications">${ico('bell')}</button><div class="page-account-shell"><button id="pageUser" class="btn btn-glass page-user-btn">${ico('user')}<span>Login</span></button><div id="pageAccountMenu" class="page-account-menu hidden"><div id="pageAccountIdentity" class="account-menu-identity"></div><a href="/profile.html">Profile</a><a href="/collection.html">My Collection</a><a href="/messages.html">Messages</a><a href="/settings.html">Settings</a><button id="pageLogout" class="danger-text">Log out</button></div></div><a class="btn btn-primary" href="/new-trade.html">${ico('plus')} Post trade</a></nav></div></header>`}
async function headerAuth(){const s=await ses(),p=s?await profile(s.user.id):null,u=$('#pageUser'),menu=$('#pageAccountMenu');if(u){u.innerHTML=s?`<img src="${esc(avatar(p))}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"><span>${esc(name(p))}</span><b class="account-chevron">⌄</b>`:`${ico('user')}<span>Discord Login</span>`;u.onclick=()=>{if(!s)return location.href='/api/discord-login';menu?.classList.toggle('hidden')}}if(s&&$('#pageAccountIdentity'))$('#pageAccountIdentity').innerHTML=`<img src="${esc(avatar(p))}"><div><b>${esc(name(p))}</b><span>@${esc(p?.username||'collector')}</span></div>`;$('#pageLogout')?.addEventListener('click',async()=>{await sb.auth.signOut();location.href='/'});$('#pageMessages')?.addEventListener('click',()=>location.href='/messages.html');$('#pageNotifications')?.addEventListener('click',()=>location.href='/notifications.html')}
async function need(){const s=await ses();if(!s)location.href='/api/discord-login';return s}
async function profilePage(){
  header(); await headerAuth();
  const s=await ses(), id=P.get('id')||s?.user.id;
  if(!id) return location.href='/api/discord-login';
  const [{data:p},{data:inv},{data:rs},{data:ts}]=await Promise.all([
    sb.from('profiles').select('*').eq('id',id).single(),
    sb.from('sprite_inventory').select('*').eq('user_id',id).eq('owned',true),
    sb.from('ratings').select('*,rater:rater_id(username,discord_name,avatar_url)').eq('rated_id',id).order('created_at',{ascending:false}),
    sb.from('trades').select('id,status').eq('user_id',id)
  ]);
  if(!p) return;
  const items=(inv||[]).map(r=>({r,s:sprite(r.sprite_id)})).filter(x=>x.s);
  const mastered=items.filter(x=>x.r.mastered).length, pct=Math.round(items.length/Math.max(sprites.length,1)*100);
  const counts={mythic:0,legendary:0,epic:0,rare:0}; items.forEach(x=>counts[x.r.rarity]=(counts[x.r.rarity]||0)+1);
  const closed=(ts||[]).filter(t=>t.status==='closed').length, open=(ts||[]).filter(t=>t.status==='open').length, own=id===s?.user.id;
  const reviewHtml=(rs||[]).length?(rs||[]).map(r=>`<article class="review-row"><div class="review-user"><img src="${esc(avatar(r.rater))}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"><b>${esc(name(r.rater))}</b></div><span class="rating">${'★'.repeat(r.stars)}</span><p>${esc(r.comment||'No written review.')}</p></article>`).join(''):'<div class="empty">No reviews yet.</div>';
  const ratingMode=P.get('rate')==='1'&&!own;
  const ratingForm=ratingMode?`<form id="pageRatingForm" class="page-card" style="padding:14px;margin-bottom:12px"><div class="page-topbar"><div><h3 style="margin:0">Rate this collector</h3><p class="subtle">Leave feedback after a completed trade.</p></div></div><label>Stars<select name="stars"><option value="5">★★★★★ — Excellent</option><option value="4">★★★★☆ — Good</option><option value="3">★★★☆☆ — Okay</option><option value="2">★★☆☆☆ — Poor</option><option value="1">★☆☆☆☆ — Bad</option></select></label><label>Comment<input name="comment" maxlength="160" placeholder="Fast, fair trade…"></label><button class="btn btn-primary" type="submit">Submit rating</button><p id="pageRatingNote" class="form-note"></p></form>`:'';
  const collectionHtml=items.length?items.map(({r,s:sp})=>`<div class="mini-sprite ${esc(sp.rarity)}" title="${esc(sp.name)}"><div class="mini-sprite-thumb"><img src="${esc(sp.image)}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"></div><span>${esc(sp.name)}</span>${r.mastered?'<b>★</b>':''}</div>`).join(''):'<div class="empty">No public Sprites collected yet.</div>';
  $('#profileRoot').innerHTML=`
    <section class="profile-page-hero">
      <div class="profile-identity"><img class="profile-avatar-xl" src="${esc(avatar(p))}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"><div><h1>${esc(name(p))}</h1><div class="profile-meta"><span>★ ${Number(p.rating_avg||0).toFixed(1)} (${p.rating_count||0})</span><span>• Joined ${new Date(p.created_at).toLocaleDateString([],{month:'short',year:'numeric'})}</span>${own?'<span class="online">● Your profile</span>':''}</div><div class="profile-meta" style="margin-top:8px"><span>Discord · @${esc(p.username||'collector')}</span></div></div></div>
      ${own?'<div style="display:flex;gap:7px"><a class="btn btn-secondary" href="/collection.html">My collection</a><a class="btn btn-secondary" href="/settings.html">Edit profile</a></div>':`<a class="btn btn-primary" href="/messages.html?peer=${encodeURIComponent(id)}">Message</a>`}
    </section>
    <div class="profile-grid-stats">
      <article class="profile-stat"><span>TRADES DONE</span><strong>${closed}</strong><small>${open} open right now</small></article>
      <article class="profile-stat"><span>SPRITES INDEXED</span><strong>${items.length}<small> / ${sprites.length}</small></strong><small>${pct}% collected</small></article>
      <article class="profile-stat"><span>MASTERED</span><strong>${mastered}</strong><small>${counts.mythic||0} mythic owned</small></article>
      <article class="profile-stat"><span>RATING</span><strong>★ ${Number(p.rating_avg||0).toFixed(1)}</strong><small>${p.rating_count||0} reviews</small></article>
    </div>
    <section class="page-card collection-summary"><div class="collection-summary-head"><b>${items.length} of ${sprites.length} Sprites collected</b><strong style="color:var(--yellow)">${pct}%</strong></div><div class="summary-bar"><i style="width:${pct}%"></i></div><div class="variant-breakdown"><div>MYTHIC <b style="float:right">${counts.mythic||0}</b></div><div>LEGENDARY <b style="float:right">${counts.legendary||0}</b></div><div>EPIC <b style="float:right">${counts.epic||0}</b></div><div>RARE <b style="float:right">${counts.rare||0}</b></div></div></section>
    <div class="profile-tabs"><button class="active" data-profile-tab="collection">Collection ${items.length}</button><button data-profile-tab="reviews">Reviews ${(rs||[]).length}</button></div>
    <section id="profileCollectionPanel" class="page-card profile-panel" style="padding:16px"><div class="page-topbar"><div><h2 style="margin:0">Collection</h2><p class="subtle">${esc(p.bio||'No bio yet.')}</p></div><span class="subtle">${mastered} mastered</span></div><div class="profile-collection-grid">${collectionHtml}</div></section>
    <section id="profileReviewsPanel" class="page-card profile-panel ${ratingMode?'':'hidden'}" style="padding:16px"><div class="page-topbar"><div><h2 style="margin:0">Reviews</h2><p class="subtle">Recent reputation from other collectors.</p></div></div>${ratingForm}<div class="profile-reviews">${reviewHtml}</div></section>`;
  if(ratingMode){$('#profileRoot').querySelectorAll('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x.dataset.profileTab==='reviews'));$('#profileCollectionPanel').classList.add('hidden');}
  $('#profileRoot').addEventListener('click',e=>{const b=e.target.closest('[data-profile-tab]');if(!b)return;$('#profileRoot').querySelectorAll('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#profileCollectionPanel').classList.toggle('hidden',b.dataset.profileTab!=='collection');$('#profileReviewsPanel').classList.toggle('hidden',b.dataset.profileTab!=='reviews');});
  $('#pageRatingForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('ratings').upsert({rater_id:s.user.id,rated_id:id,trade_id:P.get('trade')||null,stars:+f.get('stars'),comment:f.get('comment')},{onConflict:'rater_id,rated_id'});$('#pageRatingNote').textContent=error?error.message:'Rating saved.';if(!error)setTimeout(()=>location.href=`/profile.html?id=${encodeURIComponent(id)}`,500)});
}
async function collectionPage(){header();await headerAuth();const s=await need();if(!s)return;const {data:inv}=await sb.from('sprite_inventory').select('*').eq('user_id',s.user.id),map=Object.fromEntries((inv||[]).map(r=>[r.sprite_id,r]));$('#collectionRoot').innerHTML=`<div class="page-topbar"><div class="page-title"><span class="icon-tile">${ico('grid')}</span><div><h1>My Collection</h1><p>Track owned and mastered Sprites.</p></div></div><a class="btn btn-secondary" href="/profile.html">View public profile</a></div><div class="profile-collection-grid">${sprites.map(sp=>{const r=map[sp.id]||{};return `<article class="sprite-card ${esc(sp.rarity)}" data-variant="${esc(sp.variant)}"><div class="sprite-art"><span class="rarity-badge">${esc(sp.rarity)}</span><img src="${esc(sp.image)}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"></div><div class="sprite-info"><b>${esc(sp.name)}</b><div class="collect-actions"><button class="collect-btn ${r.owned?'owned':''}" data-own="${esc(sp.id)}">${r.owned?'✓ OWNED':'+ OWN'}</button><button class="collect-btn ${r.mastered?'mastered':''}" data-master="${esc(sp.id)}">${r.mastered?'★ MASTERED':'☆ MASTER'}</button></div></div></article>`}).join('')}</div>`;$('#collectionRoot').onclick=async e=>{const o=e.target.closest('[data-own]'),m=e.target.closest('[data-master]'),id=o?.dataset.own||m?.dataset.master;if(!id)return;const old=map[id]||{};let owned=!!old.owned,mastered=!!old.mastered;if(m){mastered=!mastered;if(mastered)owned=true}else{owned=!owned;if(!owned)mastered=false}const sp=sprite(id);if(!owned)await sb.from('sprite_inventory').delete().eq('user_id',s.user.id).eq('sprite_id',id);else await sb.from('sprite_inventory').upsert({user_id:s.user.id,sprite_id:id,owned,mastered,rarity:sp?.rarity||'rare'},{onConflict:'user_id,sprite_id'});location.reload()}}
async function tradePage(){header();await headerAuth();const s=await need();if(!s)return;$('#spriteNames').innerHTML=sprites.map(x=>`<option value="${esc(x.name)}">`).join('');$('#newTradeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{error}=await sb.from('trades').insert({user_id:s.user.id,offer:f.get('offer'),want:f.get('want'),tier:f.get('tier'),note:f.get('note')});$('#formNote').textContent=error?error.message:'Trade published.';if(!error)setTimeout(()=>location.href='/?#trades',500)}}
async function messagesPage(){
  header(); await headerAuth(); const s=await need(); if(!s)return;
  const uid=s.user.id;
  const {data:ms}=await sb.from('messages').select('*,sender:sender_id(id,username,discord_name,avatar_url),recipient:recipient_id(id,username,discord_name,avatar_url)').or(`sender_id.eq.${uid},recipient_id.eq.${uid}`).order('created_at',{ascending:true}).limit(1000);
  const tids=[...new Set((ms||[]).map(m=>m.trade_id).filter(Boolean))];
  let trades=[]; if(tids.length) trades=(await sb.from('trades').select('*').in('id',tids)).data||[];
  const M=new Map();
  (ms||[]).forEach(m=>{const peer=m.sender_id===uid?m.recipient_id:m.sender_id,p=m.sender_id===uid?m.recipient:m.sender,k=`${peer}::${m.trade_id||''}`,c=M.get(k)||{peer,trade:m.trade_id||'',p,rows:[],unread:0};c.rows.push(m);if(m.recipient_id===uid&&!m.read_at)c.unread++;M.set(k,c)});
  const conv=[...M.values()].sort((a,b)=>new Date(b.rows.at(-1)?.created_at||0)-new Date(a.rows.at(-1)?.created_at||0));
  let active=conv.find(c=>c.peer===P.get('peer')&&String(c.trade)===String(P.get('trade')||''))||conv[0]||null, filter='all', query='';
  const statusFor=c=>{const t=trades.find(x=>x.id===c.trade);return !t?'direct':t.status==='open'?'active':'closed'};
  const filtered=()=>conv.filter(c=>{const st=statusFor(c);if(filter==='unread'&&!c.unread)return false;if(filter==='active'&&st!=='active')return false;if(filter==='closed'&&st!=='closed')return false;const q=query.toLowerCase();return !q||name(c.p).toLowerCase().includes(q)||String(c.rows.at(-1)?.body||'').toLowerCase().includes(q)});
  async function markRead(){if(!active)return;const ids=active.rows.filter(m=>m.recipient_id===uid&&!m.read_at).map(m=>m.id);if(ids.length){await sb.from('messages').update({read_at:new Date().toISOString()}).in('id',ids);active.rows.forEach(m=>{if(ids.includes(m.id))m.read_at=new Date().toISOString()});active.unread=0}}
  function render(){
    $('#conversationList').innerHTML=filtered().length?filtered().map(c=>{const st=statusFor(c);return `<button class="conversation ${c===active?'active':''}" data-k="${esc(c.peer)}::${esc(c.trade)}"><img class="conversation-avatar-img" src="${esc(avatar(c.p))}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"><span class="conversation-main"><b class="conversation-name">${esc(name(c.p))}${c.unread?` <i class="conversation-unread">${c.unread}</i>`:''}</b><small class="conversation-preview">${esc(c.rows.at(-1)?.body||'No messages')}</small></span><span class="conversation-status ${st}">${st==='active'?'ACTIVE':st==='closed'?'CLOSED':'DM'}</span></button>`}).join(''):'<div class="message-list-empty">No conversations match this filter.</div>';
    if(!active){$('#messagesChatHead').innerHTML='<div><strong>Choose a conversation</strong><small>Trade chats and direct messages live here.</small></div>';$('#pageThread').innerHTML='<div class="message-empty-state"><strong>No conversation selected</strong><span>Open a trade and message a collector to start chatting.</span></div>';$('#messagesTrade').innerHTML='<div class="trade-side-empty"><div><b>Trade details</b><p class="subtle">Select a trade conversation.</p></div></div>';return}
    const t=trades.find(x=>x.id===active.trade), peerName=name(active.p);
    $('#messagesChatHead').innerHTML=`<div class="chat-person"><img class="chat-avatar-img" src="${esc(avatar(active.p))}" onerror="this.src='assets/spriteswap-sprite-logo-128.png'"><span><strong>${esc(peerName)}</strong><small>${t?'Trade '+esc(t.id.slice(0,8)):'Direct message'}</small></span></div><a class="btn btn-secondary btn-small" href="/profile.html?id=${encodeURIComponent(active.peer)}">Profile</a>`;
    $('#pageThread').innerHTML=active.rows.length?active.rows.map(m=>`<div class="msg-row ${m.sender_id===uid?'mine':''}"><div class="msg ${m.sender_id===uid?'mine':''}">${esc(m.body)}<small>${fmt(m.created_at)}</small></div></div>`).join(''):'<div class="message-empty-state"><strong>No messages yet</strong><span>Say hi and coordinate the trade.</span></div>';
    $('#pageThread').scrollTop=$('#pageThread').scrollHeight;
    if(t){const offer=sprites.find(sp=>sp.name.toLowerCase()===String(t.offer).toLowerCase()),want=sprites.find(sp=>sp.name.toLowerCase()===String(t.want).toLowerCase());$('#messagesTrade').innerHTML=`<div class="trade-side-head"><strong>Trade details</strong><span class="conversation-status ${t.status==='open'?'active':'closed'}">${esc(t.status.toUpperCase())}</span></div><div class="trade-side-section"><label>THEY OFFER</label><div class="trade-detail-sprite">${offer?`<img style="width:58px;height:58px;object-fit:contain;float:left;margin-right:8px" src="${esc(offer.image)}">`:''}<span>${esc(t.offer)}</span></div></div><div class="trade-swap-arrow">↕</div><div class="trade-side-section"><label>THEY WANT</label><div class="trade-detail-sprite">${want?`<img style="width:58px;height:58px;object-fit:contain;float:left;margin-right:8px" src="${esc(want.image)}">`:''}<span>${esc(t.want)}</span></div></div><div class="trade-description"><label>DESCRIPTION</label><p>${esc(t.note||'No description provided.')}</p></div><div class="trade-side-actions"><a class="trade-side-btn" href="/profile.html?id=${encodeURIComponent(active.peer)}">View trader profile</a></div>`}else $('#messagesTrade').innerHTML=`<div class="trade-side-empty"><div><b>Direct message</b><p class="subtle">This conversation is not attached to a trade.</p><a class="btn btn-secondary btn-small" href="/profile.html?id=${encodeURIComponent(active.peer)}">View profile</a></div></div>`;
  }
  render(); await markRead();
  $('#conversationList').onclick=async e=>{const b=e.target.closest('[data-k]');if(!b)return;const [peer,trade]=b.dataset.k.split('::');active=conv.find(c=>c.peer===peer&&String(c.trade)===trade);await markRead();render()};
  $('#conversationSearch').oninput=e=>{query=e.target.value;render()};
  document.querySelectorAll('[data-page-message-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.pageMessageFilter;document.querySelectorAll('[data-page-message-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});
  $('#pageMessageForm').onsubmit=async e=>{e.preventDefault();if(!active)return;const input=$('#pageMessageInput'),body=input.value.trim();if(!body)return;const {error}=await sb.from('messages').insert({sender_id:uid,recipient_id:active.peer,trade_id:active.trade||null,body});if(!error)location.reload()};
}
async function notificationsPage(){header();await headerAuth();const s=await need();if(!s)return;const {data:ms}=await sb.from('messages').select('*,sender:sender_id(username,discord_name,avatar_url)').eq('recipient_id',s.user.id).is('read_at',null).order('created_at',{ascending:false}).limit(50);$('#notificationRoot').innerHTML=`<div class="page-topbar"><div class="page-title"><span class="icon-tile">${ico('bell')}</span><div><h1>Notifications</h1><p>Your messages and trade activity.</p></div></div></div><div class="notifications-list">${(ms||[]).length?(ms||[]).map(m=>`<a class="notification-row" href="/messages.html?peer=${encodeURIComponent(m.sender_id)}&trade=${encodeURIComponent(m.trade_id||'')}"><span class="icon-tile">${ico('msg')}</span><span><b>New message from ${esc(name(m.sender))}</b><span>${esc(m.body)}</span></span><time>${fmt(m.created_at)}</time></a>`).join(''):'<div class="page-card" style="padding:30px;text-align:center">You’re all caught up.</div>'}</div>`}
async function settingsPage(){header();await headerAuth();const s=await need();if(!s)return;const p=await profile(s.user.id);$('#settingsForm').bio.value=p?.bio||'';$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{error}=await sb.from('profiles').update({bio:f.get('bio')}).eq('id',s.user.id);$('#settingsNote').textContent=error?error.message:'Saved.'}}

async function reportPage(){header();await headerAuth();const s=await need();if(!s)return;$('#reportPageForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{error}=await sb.from('reports').insert({reporter_id:s.user.id,reported_user_id:P.get('user')||null,trade_id:P.get('trade')||null,reason:f.get('reason'),details:f.get('details')});$('#reportPageNote').textContent=error?error.message:'Report sent to moderators.';if(!error)e.target.reset()}}
async function adminPage(){header();await headerAuth();const s=await need();if(!s)return;const p=await profile(s.user.id);if(!p?.is_admin){$('#adminPageRoot').innerHTML='<div class="empty">Admin access required.</div>';return}const {data:rows}=await sb.from('reports').select('*,reporter:reporter_id(username,discord_name),reported:reported_user_id(username,discord_name)').order('created_at',{ascending:false}).limit(100);$('#adminPageRoot').innerHTML=(rows||[]).length?(rows||[]).map(r=>`<div class="admin-row"><div><b>${esc(r.reason)}</b> <span class="tier">${esc(r.status)}</span><div class="subtle">Reporter ${esc(name(r.reporter))} · Target ${esc(name(r.reported))}</div><p>${esc(r.details||'No details')}</p></div><div class="admin-actions"><button class="btn btn-secondary btn-small" data-status="${r.id}:reviewed">reviewed</button><button class="btn btn-secondary btn-small" data-status="${r.id}:dismissed">dismissed</button><button class="btn btn-danger btn-small" data-status="${r.id}:actioned">actioned</button></div></div>`).join(''):'<div class="empty">No reports.</div>';$('#adminPageRoot').onclick=async e=>{const b=e.target.closest('[data-status]');if(!b)return;const [id,status]=b.dataset.status.split(':');await sb.from('reports').update({status}).eq('id',id);location.reload()}}

document.addEventListener('DOMContentLoaded',()=>{const p=document.body.dataset.page;if(p==='profile')profilePage();if(p==='collection')collectionPage();if(p==='messages')messagesPage();if(p==='new-trade')tradePage();if(p==='notifications')notificationsPage();if(p==='settings')settingsPage();if(p==='report')reportPage();if(p==='admin')adminPage()});
})();
